apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: prova
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  type: LoadBalancer
  ports:
  - name: http
    port: 5601
    targetPort: 5601
    protocol: TCP
