apiVersion: v1
kind: Service
metadata:
  name: simpleapp-python-service
  namespace: prova
spec:
  selector:
    app: simpleapp-python
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: ClusterIP
